update&fix manuals
stax76/mpv.net pull request #317
Opened 2021-08-29 18:43 UTC by hooke007

To update the manual_chs;

For orig manual, I deleted the contents about everything™。

2021-08-30 12:48 UTC, stax76 commented on src/Misc/CorePlayer.cs
> -        public static string[] SubtitleTypes { get; } = { "srt", "ass", "idx", "sup", "ttxt", "ssa", "smi" };
There is a ttxt subtitle format:

https://fileinfo.com/extension/ttxt

2021-08-31 17:08 UTC, hooke007 commented
I also fixed the wrong default values in the editor.

https://github.com/stax76/mpv.net/blob/42c623c8cae8e13928582c91505d26fb4bdefc60/src/Resources/mpv.conf.txt#L5-L6

2021-09-01 16:37 UTC, hooke007 commented
`watch-later-options = start` would cause the recording the start time twice, so fix it.

2021-09-02 11:02 UTC, stax76 requested changes

2021-09-02 11:05 UTC, stax76 commented
> watch-later-options = start would cause the recording the start time twice, so fix it.

OK, I understand it now.

2021-09-02 11:06 UTC, hooke007 commented on src/Resources/mpv.conf.txt
> +watch-later-options =
start will cause the issue here
https://github.com/mpv-player/mpv/issues/9174

2021-09-02 11:07 UTC, hooke007 commented
>as default in the mpv manual.

I know it, but you set the different value in the initial conf

2021-09-02 11:48 UTC, hooke007 commented
![Snipaste_2021-09-02_19-46-49](https://user-images.githubusercontent.com/41094733/131838197-515d73dd-b584-4bec-9a2b-85fc6a79ae37.jpg)
This can avoid the extra output in console when users drag the window. And it would not affect the other functions.

2021-09-02 12:39 UTC, stax76 commented
You can put `MBTN_LEFT  ignore` in input.conf, I don't know why it didn't make it into the defaults of input.conf.

2021-09-02 12:42 UTC, merged

2021-09-02 13:09 UTC, stax76 commented
Empty watch-later-options is not compatible with the conf editor, the related code is complex, for now I work around it setting the default to:

watch-later-options = mute

Not sure if this creates a new problem.

2021-09-02 13:23 UTC, hooke007 commented
> Not sure if this creates a new problem.

I have a better idea `watch-later-options = vid`
It usually have no side effect.